# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'NeverForget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeverForget

	pod 'GoogleMaps', '7.0.0'

  target 'NeverForgetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeverForgetUITests' do
    # Pods for testing
  end

end
