//
//  LoginModels.swift
//  NeverForget
//
//  Created by Jaber Shamali on 23/06/22.
//  Copyright (c) 2022 Jabinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login{
    // MARK: Use cases
    
    enum Something{
        struct Request{
        }
        struct Response{
        }
        struct ViewModel{
        }
    }
    
    enum LoginView{
        struct Request{
//            let view : UIView
        }
        struct Response{
            let view : UIView
        }
        struct ViewModel{
            let view : UIView
        }
    }
    
    enum MapView{
        struct Request{
        }
        struct Response{
        }
        struct ViewModel{
        }
    }
}
