//
//  LoginPresenter.swift
//  NeverForget
//
//  Created by Jaber Shamali on 23/06/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic{
    func presentSomething(response: Login.Something.Response)
    func presentView(response: Login.LoginView.Response)

}

class LoginPresenter: LoginPresentationLogic{
     var viewController: LoginDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Login.Something.Response){
        let viewModel = Login.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentView(response: Login.LoginView.Response){
        let viewModel = Login.LoginView.ViewModel(view: LoginView())
        viewController?.displayView(viewModel: viewModel)
    }
}
