//
//  LoginPresenter.swift
//  NeverForget
//
//  Created by Jaber Shamali on 23/06/22.
//  Copyright (c) 2022 Jabinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic{
    func presentSomething(response: Login.Something.Response)
    func presentView(response: Login.LoginView.Response)
    func presentMapView()
    func presentItemView()

}

class LoginPresenter: LoginPresentationLogic{
    
     var viewController: (LoginDisplayLogic & LoginViewControllerDelegate)?
    
    // MARK: Do something
    
    func presentSomething(response: Login.Something.Response){
        let viewModel = Login.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentView(response: Login.LoginView.Response){
        let loginView: LoginView = .init()
        loginView.delegate = viewController
        let viewModel = Login.LoginView.ViewModel(view: loginView)
        viewController?.displayView(viewModel: viewModel)
    }
    
    func presentMapView() {
        viewController?.displayMap()
    }
    
    func presentItemView() {
        viewController?.displayList()

    }
}
