//
//  MapInteractor.swift
//  NeverForget
//
//  Created by Jaber Shamali on 24/06/22.
//  Copyright (c) 2022 Jabinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapBusinessLogic{
//    func doMap(request: Map.MapView.Request)
    func doMap()
}

protocol MapDataStore{
    //var name: String { get set }
}

class MapInteractor: MapBusinessLogic, MapDataStore{
    var presenter: MapPresentationLogic?
    var worker: MapWorker?

    func doMap(){        
        let response = Map.MapView.Response(view: MapView())
        presenter?.presentMap(response: response)
    }
}
