//
//  ItemWorker.swift
//  NeverForget
//
//  Created by Jaber Shamali on 26/06/22.
//  Copyright (c) 2022 Jabinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ItemWorker
{
  func doSomeWork()
  {
  }
}
