//
//  ItemPresenter.swift
//  NeverForget
//
//  Created by Jaber Shamali on 26/06/22.
//  Copyright (c) 2022 Jabinho. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemPresentationLogic{
//    func presentSomething(response: Item.Something.Response)
}

class ItemPresenter: ItemPresentationLogic{
    var viewController: ItemDisplayLogic?
    
    // MARK: Do something
//
//    func presentSomething(response: Item.Something.Response){
//        let viewModel = Item.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
